name: my-spring-boot-app
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
services:
  - name: Build backend
        run: |
          cd backend
          mvn clean package

      - name: Run backend
        run: |
          cd backend
          java -jar target/my-spring-boot-app.jar
